name: Scan Nginx Web Server

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Nginx
      run: |
          sudo apt-get install nginx -y
          sudo cp ./tests/web_servers/nginx/default  /etc/nginx/sites-available/default

    - name: Start Nginx
      # Start nginx and display the status if it starting it failed
      run: sudo /etc/init.d/nginx restart || systemctl status nginx.service

    - name: Install pip
      run: |
        python -m pip install --upgrade pip pipenv setuptools

    - name: Install SSLyze
      run: python setup.py install

    - name: Scan web server
      run: python tests/web_servers/scan_localhost.py nginx
